name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure
    - name: Build with Makefile
      run: make
    - name: Run tests
      run: ./main
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
